import ProductionType from './ProductionType.js';

/**
 * Keywords that may be used as `Literal` `word`s in an object's defined syntax.
 * @constant
 */
const keywordsPermissibleAsLiterals = new Set<ProductionType>([
  ProductionType._ABSENT,
  ProductionType._ABSTRACT_SYNTAX,
  ProductionType._ALL,
  ProductionType._ANY,
  ProductionType._APPLICATION,
  ProductionType._AUTOMATIC,
  ProductionType._BEGIN,
  ProductionType._BY,
  ProductionType._CLASS,
  ProductionType._COMPONENT,
  ProductionType._COMPONENTS,
  ProductionType._CONSTRAINED,
  ProductionType._CONTAINING,
  ProductionType._DATE,
  ProductionType._DATE_TIME,
  ProductionType._DEFAULT,
  ProductionType._DEFINED,
  ProductionType._DEFINITIONS,
  ProductionType._DURATION,
  ProductionType._ENCODED,
  ProductionType._ENCODING_CONTROL,
  ProductionType._EXCEPT,
  ProductionType._EXPLICIT,
  ProductionType._EXPORTS,
  ProductionType._EXTENSIBILITY,
  ProductionType._FROM,
  ProductionType._IDENTIFIER,
  ProductionType._IMPLICIT,
  ProductionType._IMPLIED,
  ProductionType._IMPORTS,
  ProductionType._INCLUDES,
  ProductionType._INSTRUCTIONS,
  ProductionType._MACRO,
  ProductionType._MAX,
  ProductionType._MIN,
  ProductionType._NOTATION,
  ProductionType._OF,
  ProductionType._OPTIONAL,
  ProductionType._PATTERN,
  ProductionType._PDV,
  ProductionType._PRESENT,
  ProductionType._PRIVATE,
  ProductionType._SETTINGS,
  ProductionType._SIZE,
  ProductionType._STRING,
  ProductionType._SYNTAX,
  ProductionType._TAGS,
  ProductionType._TIME,
  ProductionType._TIME_OF_DAY,
  ProductionType._TYPE,
  ProductionType._TYPE_IDENTIFIER,
  ProductionType._VALUE,
  ProductionType._UNIQUE,
  ProductionType._UNIVERSAL,
  ProductionType._WITH,
]);

export default keywordsPermissibleAsLiterals;
