AbsoluteReference ::= "@" ModuleIdentifier "." ItemSpec
ActualParameter ::= Type | Value | ValueSet | DefinedObjectClass | Object | ObjectSet
ActualParameterList ::= "{" ActualParameter "," + "}"
AdditionalElementSetSpec ::= ElementSetSpec
AdditionalEnumeration ::= Enumeration
AlternativeTypeList ::= NamedType | AlternativeTypeList "," NamedType
AlternativeTypeLists ::= RootAlternativeTypeList | RootAlternativeTypeList "," ExtensionAndException ExtensionAdditionAlternatives OptionalExtensionMarker
ArcIdentifier ::= integerUnicodeLabel | non-integerUnicodeLabel
AssignedIdentifier ::= ObjectIdentifierValue | DefinedValue | empty
Assignment ::= TypeAssignment | ValueAssignment | XMLValueAssignment | ValueSetTypeAssignment | ObjectClassAssignment | ObjectAssignment | ObjectSetAssignment | ParameterizedAssignment
AssignmentList ::= Assignment | AssignmentList Assignment
AtNotation ::= "@" ComponentIdList | "@." Level ComponentIdList
BitStringType ::= BIT STRING | BIT STRING "{" NamedBitList "}"
BitStringValue ::= bstring | hstring | "{" IdentifierList "}" | "{" "}" | CONTAINING Value
BooleanType ::= BOOLEAN
BooleanValue ::= TRUE | FALSE
BuiltinType ::= BitStringType | BooleanType | CharacterStringType | ChoiceType | DateType | DateTimeType | DurationType | EmbeddedPDVType | EnumeratedType | ExternalType | InstanceOfType | IntegerType | IRIType | NullType | ObjectClassFieldType | ObjectIdentifierType | OctetStringType | RealType | RelativeIRIType | RelativeOIDType | SequenceType | SequenceOfType | SetType | SetOfType | PrefixedType | TimeType | TimeOfDayType
BuiltinValue ::= BitStringValue | BooleanValue | CharacterStringValue | ChoiceValue | EmbeddedPDVValue | EnumeratedValue | ExternalValue | InstanceOfValue | IntegerValue | IRIValue | NullValue | ObjectIdentifierValue | OctetStringValue | RealValue | RelativeIRIValue | RelativeOIDValue | SequenceValue | SequenceOfValue | SetValue | SetOfValue | PrefixedValue | TimeValue
Cell ::= number
CharacterStringList ::= "{" CharSyms "}"
CharacterStringType ::= RestrictedCharacterStringType | UnrestrictedCharacterStringType
CharacterStringValue ::= RestrictedCharacterStringValue | UnrestrictedCharacterStringValue
CharsDefn ::= cstring | Quadruple | Tuple | DefinedValue
CharSyms ::= CharsDefn | CharSyms "," CharsDefn
ChoiceType ::= CHOICE "{" AlternativeTypeLists "}"
ChoiceValue ::= identifier ":" Value
Class ::= UNIVERSAL | APPLICATION | PRIVATE | empty
ClassNumber ::= number | DefinedValue
ComponentConstraint ::= ValueConstraint PresenceConstraint
ComponentId ::= identifier | number | "*"
ComponentIdList ::= identifier "." +
ComponentRelationConstraint ::= "{" DefinedObjectSet "}" "{" AtNotation "," + "}"
ComponentType ::= NamedType | NamedType OPTIONAL | NamedType DEFAULT Value | COMPONENTS OF Type
ComponentTypeList ::= ComponentType | ComponentTypeList "," ComponentType
ComponentTypeLists ::= RootComponentTypeList | RootComponentTypeList "," ExtensionAndException ExtensionAdditions OptionalExtensionMarker | RootComponentTypeList "," ExtensionAndException ExtensionAdditions ExtensionEndMarker  "," RootComponentTypeList | ExtensionAndException ExtensionAdditions ExensionEndMarker "," RootComponentTypeList | ExtensionAndException ExtensionAdditions OptionalExtensionMarker
ComponentValueList ::= NamedValue | ComponentValueList "," NamedValue
ConstrainedType ::= Type Constraint | TypeWithConstraint
Constraint ::= "(" ConstraintSpec ExceptionSpec ")"
ConstraintSpec ::= SubtypeConstraint | GeneralConstraint
ContainedSubtype ::= Includes Type
ContentsConstraint ::= CONTAINING Type | ENCODED BY Value | CONTAINING Type ENCODED BY Value
DateTimeType ::= DATE-TIME
DateType ::= DATE
DefaultSyntax ::= "{" FieldSetting "," * "}"
DefinedObject ::= ExternalObjectReference | objectreference
DefinedObjectClass ::= ExternalObjectClassReference | objectclassreference | UsefulObjectClassReference
DefinedObjectSet ::= ExternalObjectSetReference | objectsetreference
DefinedSyntax ::= "{" DefinedSyntaxToken empty * "}"
DefinedSyntaxToken ::= Literal | Setting
DefinedType ::= ExternalTypeReference | typereference | ParameterizedType | ParameterizedValueSetType
DefinedValue ::= ExternalValueReference | valuereference | ParameterizedValue
DefinitiveIdentification ::= DefinitiveOID | DefinitiveOIDandIRI | empty
DefinitiveNameAndNumberForm ::= identifier "(" DefinitiveNumberForm ")"
DefinitiveNumberForm ::= number
DefinitiveObjIdComponent ::= NameForm | DefinitiveNumberForm | DefinitiveNameAndNumberForm
DefinitiveObjIdComponentList ::= DefinitiveObjIdComponent | DefinitiveObjIdComponent DefinitiveObjIdComponentList
DefinitiveOID ::= "{" DefinitiveObjIdComponentList "}"
DefinitiveOIDandIRI ::= DefinitiveOID IRIValue
DummyGovernor ::= DummyReference
DummyReference ::= Reference
DurationRange ::= ValueRange
DurationType ::= DURATION
Elements ::= SubtypeElements | ObjectSetElements | "(" ElementSetSpec ")"
ElementSetSpec ::= Unions | ALL Exclusions
ElementSetSpecs ::= RootElementSetSpec | RootElementSetSpec "," "..." | RootElementSetSpec "," "..." "," AdditionalElementSetSpec
Elems ::= Elements
EmbeddedPDVType ::= EMBEDDED PDV
EmbeddedPDVValue ::= SequenceValue
EmptyElementBoolean ::= "<" & "true" "/>" | "<" & "false" "/>"
EmptyElementEnumerated ::= "<" & identifier "/>"
EmptyElementInteger ::= "<" & identifier "/>"
EmptyElementList ::= "<" & identifier "/>" | EmptyElementList "<" & identifier "/>"
EmptyElementReal ::= "<" & PLUS-INFINITY "/>" | "<" & MINUS-INFINITY "/>" | "<" & NOT-A-NUMBER "/>"
EncodingControlSection ::= ENCODING-CONTROL encodingreference
EncodingControlSections ::= EncodingControlSection EncodingControlSections | empty
EncodingPrefix ::= "[" EncodingReference EncodingInstruction "]"
EncodingPrefix ::= "[" EncodingReference EncodingInstruction "]"
EncodingPrefixedType ::= EncodingPrefix Type
EncodingPrefixedType ::= EncodingPrefix Type
EncodingReference ::= encodingreference ":" | empty
EncodingReferenceDefault ::= encodingreference INSTRUCTIONS | empty
EnumeratedType ::= ENUMERATED "{" Enumerations "}"
EnumeratedValue ::= identifier
Enumeration ::= EnumerationItem | EnumerationItem "," Enumeration
EnumerationItem ::= identifier | NamedNumber
Enumerations ::= RootEnumeration | RootEnumeration "," "..." ExceptionSpec | RootEnumeration "," "..." ExceptionSpec "," AdditionalEnumeration
ExceptionIdentification ::= SignedNumber | DefinedValue | Type ":" Value
ExceptionSpec ::= "!" ExceptionIdentification | empty
Exclusions ::= EXCEPT Elements
Exports ::= EXPORTS SymbolsExported ";" | EXPORTS ALL ";" | empty
ExtensionAddition ::= ComponentType | ExtensionAdditionGroup
ExtensionAdditionAlternative ::= ExtensionAdditionAlternativesGroup | NamedType
ExtensionAdditionAlternatives ::= "," ExtensionAdditionAlternativesList | empty
ExtensionAdditionAlternativesGroup ::= "[[" VersionNumber AlternativeTypeList "]]"
ExtensionAdditionAlternativesList ::= ExtensionAdditionAlternative | ExtensionAdditionAlternativesList "," ExtensionAdditionAlternative
ExtensionAdditionGroup ::= "[[" VersionNumber ComponentTypeList "]]"
ExtensionAdditionList ::= ExtensionAddition | ExtensionAdditionList "," ExtensionAddition
ExtensionAdditions ::= "," ExtensionAdditionList | empty
ExtensionAndException ::= "..." | "..." ExceptionSpec
ExtensionDefault ::= EXTENSIBILITY IMPLIED | empty
ExtensionEndMarker ::= "," "..."
ExternalObjectClassReference ::= modulereference "." objectclassreference
ExternalObjectReference ::= modulereference "." objectreference
ExternalObjectSetReference ::= modulereference "." objectsetreference
ExternalType ::= EXTERNAL
ExternalTypeReference ::= modulereference "." typereference
ExternalValue ::= SequenceValue
ExternalValueReference ::= modulereference "." valuereference
FieldName ::= PrimitiveFieldName "." +
FieldSetting ::= PrimitiveFieldName Setting
FieldSpec ::= TypeFieldSpec | FixedTypeValueFieldSpec | VariableTypeValueFieldSpec | FixedTypeValueSetFieldSpec | VariableTypeValueSetFieldSpec | ObjectFieldSpec | ObjectSetFieldSpec
FirstArcIdentifier ::= "/" ArcIdentifier
FirstRelativeArcIdentifier ::= ArcIdentifier
FixedTypeFieldVal ::= BuiltinValue | ReferencedValue
FixedTypeValueSetFieldSpec ::= valuesetfieldreference Type ValueSetOptionalitySpec ?
FullSpecification ::= "{" TypeConstraints "}"
GeneralConstraint ::= UserDefinedConstraint | TableConstraint | ContentsConstraint
GlobalModuleReference ::= modulereference AssignedIdentifier
Governor ::= Type | DefinedObjectClass
Group ::= number
IdentifierList ::= identifier | IdentifierList "," identifier
IElems ::= Intersections
Imports ::= IMPORTS SymbolsImported ";" | empty
Includes ::= INCLUDES | empty
InformationFromObjects ::= ValueFromObject | ValueSetFromObjects | TypeFromObject | ObjectFromObject | ObjectSetFromObjects
InnerTypeConstraints ::= WITH COMPONENT SingleTypeConstraint | WITH COMPONENTS MultipleTypeConstraints
InstanceOfType ::= INSTANCE OF DefinedObjectClass
InstanceOfValue ::= Value
IntegerType ::= INTEGER | INTEGER "{" NamedNumberList "}"
IntegerValue ::= SignedNumber | identifier
IntersectionElements ::= Elements | Elems Exclusions
IntersectionMark ::= "^" | INTERSECTION
Intersections ::= IntersectionElements | IElems IntersectionMark IntersectionElements
IRIType ::= OID-IRI
IRIValue ::= """ FirstArcIdentifier SubsequentArcIdentifier """
ItemId ::= ItemSpec
ItemSpec ::= typereference | ItemId "." ComponentId
Level ::= "." Level | empty
Literal ::= word | ","
LowerEndpoint ::= LowerEndValue | LowerEndValue "<"
LowerEndValue ::= Value | MIN
ModuleBody ::= Exports Imports AssignmentList | empty
ModuleDefinition ::= ModuleIdentifier DEFINITIONS EncodingReferenceDefault TagDefault ExtensionDefault "::=" BEGIN ModuleBody EncodingControlSections END
ModuleIdentifier ::= modulereference DefinitiveIdentification
MultipleTypeConstraints ::= FullSpecification | PartialSpecification
NameAndNumberForm ::= identifier "(" NumberForm ")"
NamedBit ::= identifier "(" number ")" | identifier "(" DefinedValue ")"
NamedBitList ::= NamedBit | NamedBitList "," NamedBit
NamedConstraint ::= identifier ComponentConstraint
NamedNumber ::= identifier "(" SignedNumber ")" | identifier "(" DefinedValue ")"
NamedNumberList ::= NamedNumber | NamedNumberList "," NamedNumber
NamedType ::= identifier Type
NamedValue ::= identifier Value
NamedValueList ::= NamedValue | NamedValueList "," NamedValue
NameForm ::= identifier
NonParameterizedTypeName ::= ExternalTypeReference | typereference | xmlasn1typename
NullType ::= NULL
NullValue ::= NULL
NumberForm ::= number | DefinedValue
NumericRealValue ::= realnumber | "-" realnumber | SequenceValue
Object ::= DefinedObject | ObjectDefn | ObjectFromObject |  ParameterizedObject
ObjectAssignment ::= objectreference DefinedObjectClass "::=" Object
ObjectClass ::= DefinedObjectClass | ObjectClassDefn | ParameterizedObjectClass
ObjectClassAssignment ::= objectclassreference "::=" ObjectClass
ObjectClassDefn ::= CLASS "{" FieldSpec "," + "}" WithSyntaxSpec?
ObjectClassFieldType ::= DefinedObjectClass "." FieldName
ObjectClassFieldValue ::= OpenTypeFieldVal | FixedTypeFieldVal
ObjectDefn ::= DefaultSyntax | DefinedSyntax
ObjectFieldSpec ::= objectfieldreference DefinedObjectClass ObjectOptionalitySpec?
ObjectFromObject ::= ReferencedObjects "." FieldName
ObjectIdentifierType ::= OBJECT IDENTIFIER
ObjectIdentifierValue ::= "{" ObjIdComponentsList "}" | "{" DefinedValue ObjIdComponentsList "}"
ObjectOptionalitySpec ::= OPTIONAL | DEFAULT Object
ObjectSet ::= "{" ObjectSetSpec "}"
ObjectSetAssignment ::= objectsetreference DefinedObjectClass "::=" ObjectSet
ObjectSetElements ::= Object | DefinedObjectSet | ObjectSetFromObjects | ParameterizedObjectSet
ObjectSetFieldSpec ::= objectsetfieldreference DefinedObjectClass ObjectSetOptionalitySpec ?
ObjectSetFromObjects ::= ReferencedObjects "." FieldName
ObjectSetOptionalitySpec ::= OPTIONAL | DEFAULT ObjectSet
ObjectSetSpec ::= RootElementSetSpec | RootElementSetSpec "," "..." | "..." | "..." "," AdditionalElementSetSpec | RootElementSetSpec "," "..." "," AdditionalElementSetSpec
ObjIdComponents ::= NameForm | NumberForm | NameAndNumberForm | DefinedValue
ObjIdComponentsList ::= ObjIdComponents | ObjIdComponents ObjIdComponentsList
OctetStringType ::= OCTET STRING
OctetStringValue ::= bstring | hstring | CONTAINING Value
OpenTypeFieldVal ::= Type ":" Value
OptionalExtensionMarker ::= "," "..." | empty
OptionalGroup ::= "[" TokenOrGroupSpec empty + "]"
Parameter ::= ParamGovernor ":" DummyReference | DummyReference
ParameterizedAssignment ::= ParameterizedTypeAssignment | ParameterizedValueAssignment | ParameterizedValueSetTypeAssignment | ParameterizedObjectClassAssignment | ParameterizedObjectAssignment | ParameterizedObjectSetAssignment
ParameterizedObject ::= DefinedObject ActualParameterList
ParameterizedObjectAssignment ::= objectreference ParameterList DefinedObjectClass "::=" Object
ParameterizedObjectClass ::= DefinedObjectClass ActualParameterList
ParameterizedObjectClassAssignment ::= objectclassreference ParameterList "::=" ObjectClass
ParameterizedObjectSet ::= DefinedObjectSet ActualParameterList
ParameterizedObjectSetAssignment ::= objectsetreference ParameterList DefinedObjectClass "::=" ObjectSet
ParameterizedReference ::= Reference | Reference "{"  "}"
ParameterizedType ::= SimpleDefinedType ActualParameterList
ParameterizedTypeAssignment ::= typereference ParameterList "::=" Type
ParameterizedValue ::= SimpleDefinedValue ActualParameterList
ParameterizedValueAssignment ::= valuereference ParameterList Type "::=" Value
ParameterizedValueSetType ::= SimpleDefinedType ActualParameterList
ParameterizedValueSetTypeAssignment ::= typereference ParameterList Type "::=" ValueSet
ParameterList ::= "{" Parameter "," + "}"
ParamGovernor ::= Governor | DummyGovernor
PartialSpecification ::= "{" "..." "," TypeConstraints "}"
PatternConstraint ::= PATTERN Value
PermittedAlphabet ::= FROM Constraint
Plane ::= number
PrefixedType ::= TaggedType | EncodingPrefixedType
PrefixedValue ::= Value
PresenceConstraint ::= PRESENT | ABSENT | OPTIONAL | empty
PrimitiveFieldName ::= typefieldreference | valuefieldreference | valuesetfieldreference | objectfieldreference | objectsetfieldreference
PropertyAndSettingPair ::= PropertyName "=" SettingName
PropertyName ::= psname
PropertySettings ::= SETTINGS simplestring
PropertySettingsList ::= PropertyAndSettingPair | PropertySettingsList PropertyAndSettingPair
Quadruple ::= "{" Group "," Plane "," Row "," Cell "}"
RealType ::= REAL
RealValue ::= NumericRealValue | SpecialRealValue
RecurrenceRange ::= ValueRange
Reference ::= typereference | valuereference | objectclassreference | objectreference | objectsetreference
ReferencedObjects ::= DefinedObject | ParameterizedObject | DefinedObjectSet | ParameterizedObjectSet
ReferencedType ::= DefinedType | UsefulType | SelectionType | TypeFromObject | ValueSetFromObjects
ReferencedValue ::= DefinedValue | ValueFromObject
RelativeIRIType ::= RELATIVE-OID-IRI
RelativeIRIValue ::= """ FirstRelativeArcIdentifier SubsequentArcIdentifier """
RelativeOIDComponents ::= NumberForm | NameAndNumberForm | DefinedValue
RelativeOIDComponentsList ::= RelativeOIDComponents | RelativeOIDComponents RelativeOIDComponentsList
RelativeOIDType ::= RELATIVE-OID
RelativeOIDValue ::= "{" RelativeOIDComponentsList "}"
RequiredToken ::= Literal | PrimitiveFieldName
RestrictedCharacterStringType ::= BMPString | GeneralString | GraphicString | IA5String | ISO646String | NumericString | PrintableString | TeletexString | T61String | UniversalString | UTF8String | VideotexString | VisibleString
RestrictedCharacterStringValue ::= cstring | CharacterStringList | Quadruple | Tuple
RootAlternativeTypeList ::= AlternativeTypeList
RootComponentTypeList ::= ComponentTypeList
RootElementSetSpec ::= ElementSetSpec
RootEnumeration ::= Enumeration
Row ::= number
SelectionType ::= identifier "<" Type
SequenceOfType ::= SEQUENCE OF Type | SEQUENCE OF NamedType
SequenceOfValue ::= "{" ValueList "}" | "{" NamedValueList "}" | "{" "}"
SequenceType ::= SEQUENCE "{" "}" | SEQUENCE "{" ExtensionAndException OptionalExtensionMarker "}" | SEQUENCE "{" ComponentTypeLists "}"
SequenceValue ::= "{" ComponentValueList "}" | "{" "}"
SetOfType ::= SET OF Type | SET OF NamedType
SetOfValue ::= "{" ValueList "}" | "{" NamedValueList "}" | "{" "}"
Setting ::= Type | Value | ValueSet | Object | ObjectSet
SettingName ::= psname
SetType ::= SET "{" "}" | SET "{" ExtensionAndException OptionalExtensionMarker "}" | SET "{" ComponentTypeLists "}"
SetValue ::= "{" ComponentValueList "}" | "{" "}"
SignedNumber ::= number | "-" number
SimpleDefinedType ::= ExternalTypeReference | typereference
SimpleDefinedValue ::= ExternalValueReference | valuereference
SimpleTableConstraint ::= ObjectSet
SingleTypeConstraint ::= Constraint
SingleValue ::= Value
SizeConstraint ::= SIZE Constraint
SpecialRealValue ::= PLUS-INFINITY | MINUS-INFINITY | NOT-A-NUMBER
SubsequentArcIdentifier ::= "/" ArcIdentifier SubsequentArcIdentifier | empty
SubtypeConstraint ::= ElementSetSpecs
SubtypeElements ::= SingleValue | ContainedSubtype | ValueRange | PermittedAlphabet | SizeConstraint | TypeConstraint | InnerTypeConstraints | PatternConstraint | PropertySettings | DurationRange | TimePointRange | RecurrenceRange
Symbol ::= Reference | ParameterizedReference
SymbolList ::= Symbol | SymbolList "," Symbol
SymbolsExported ::= SymbolList | empty
SymbolsFromModule ::= SymbolList FROM GlobalModuleReference
SymbolsFromModuleList ::= SymbolsFromModule | SymbolsFromModuleList SymbolsFromModule
SymbolsImported ::= SymbolsFromModuleList | empty
SyntaxList ::= "{" TokenOrGroupSpec empty + "}"
TableColumn ::= number
TableConstraint ::= SimpleTableConstraint | ComponentRelationConstraint
TableRow ::= number
Tag ::= "[" EncodingReference Class ClassNumber "]"
TagDefault ::= EXPLICIT TAGS | IMPLICIT TAGS | AUTOMATIC TAGS | empty
TaggedType ::= Tag Type | Tag IMPLICIT Type | Tag EXPLICIT Type
TextBoolean ::= extended-true | extended-false
TextEnumerated ::= identifier
TextInteger ::= identifier
TextList ::= identifier | TextList identifier
TextReal ::= "INF" | "-" & "INF" | "NaN"
TimeOfDayType ::= TIME-OF-DAY
TimePointRange ::= ValueRange
TimeType ::= TIME
TimeValue ::= tstring
TokenOrGroupSpec ::= RequiredToken | OptionalGroup
Tuple ::= "{" TableColumn "," TableRow "}"
Type ::= BuiltinType | ReferencedType | ConstrainedType
TypeAssignment ::= typereference "::=" Type
TypeConstraint ::= Type
TypeConstraints ::= NamedConstraint | NamedConstraint "," TypeConstraints
TypeFieldSpec ::= typefieldreference TypeOptionalitySpec?
TypeFixedTypeValueFieldSpec ::= valuefieldreference Type UNIQUE? ValueOptionalitySpec ?
TypeFromObject ::= ReferencedObjects "." FieldName
TypeOptionalitySpec ::= OPTIONAL | DEFAULT
TypeWithConstraint ::= SET Constraint OF Type | SET SizeConstraint OF Type | SEQUENCE Constraint OF Type | SEQUENCE SizeConstraint OF Type | SET Constraint OF NamedType | SET SizeConstraint OF NamedType | SEQUENCE Constraint OF NamedType | SEQUENCE SizeConstraint OF NamedType
UElems ::= Unions
UnionMark ::= "|" | UNION
Unions ::= Intersections | UElems UnionMark Intersections
UnrestrictedCharacterStringType ::= CHARACTER STRING
UnrestrictedCharacterStringValue ::= SequenceValue
UpperEndpoint ::= UpperEndValue | "<" UpperEndValue
UpperEndValue ::= Value | MAX
UsefulObjectClassReference ::= TYPE-IDENTIFIER | ABSTRACT-SYNTAX
UsefulType ::= typereference
UserDefinedConstraint ::= CONSTRAINED BY "{" UserDefinedConstraintParameter "," * "}"
UserDefinedConstraintParameter ::= Governor ":" Value | Governor ":" Object | DefinedObjectSet | Type | DefinedObjectClass
Value ::= BuiltinValue | ReferencedValue | ObjectClassFieldValue
ValueAssignment ::= valuereference Type "::=" Value
ValueConstraint ::= Constraint | empty
ValueFromObject ::= ReferencedObjects "." FieldName
ValueList ::= Value | ValueList "," Value
ValueOptionalitySpec ::= OPTIONAL | DEFAULT Value
ValueRange ::= LowerEndpoint ".." UpperEndpoint
ValueSet ::= "{" ElementSetSpecs "}"
ValueSetFromObjects ::= ReferencedObjects "." FieldName
ValueSetOptionalitySpec ::= OPTIONAL | DEFAULT ValueSet
ValueSetTypeAssignment ::= typereference Type "::=" ValueSet
VariableTypeValueFieldSpec ::= valuefieldreference FieldName ValueOptionalitySpec ?
VariableTypeValueSetFieldSpec ::= valuesetfieldreference FieldName ValueSetOptionalitySpec?
VersionNumber ::= empty | number ":"
WithSyntaxSpec ::= WITH SYNTAX SyntaxList
XMLBitStringValue ::= XMLTypedValue | xmlbstring | XMLIdentifierList | empty
XMLBooleanValue ::= EmptyElementBoolean | TextBoolean
XMLBuiltinValue ::= XMLBitStringValue | XMLBooleanValue | XMLCharacterStringValue | XMLChoiceValue | XMLEmbeddedPDVValue | XMLEnumeratedValue | XMLExternalValue | XMLInstanceOfValue | XMLIntegerValue | XMLIRIValue | XMLNullValue | XMLObjectIdentifierValue | XMLOctetStringValue | XMLRealValue | XMLRelativeIRIValue | XMLRelativeOIDValue | XMLSequenceValue | XMLSequenceOfValue | XMLSetValue | XMLSetOfValue | XMLPrefixedValue | XMLTimeValue
XMLCharacterStringValue ::= XMLRestrictedCharacterStringValue | XMLUnrestrictedCharacterStringValue
XMLChoiceValue ::= "<" & identifier ">" XMLValue "</" & identifier ">"
XMLComponentValueList ::= XMLNamedValue | XMLComponentValueList XMLNamedValue
XMLDelimitedItem ::= "<" & NonParameterizedTypeName ">" XMLValue "</" & NonParameterizedTypeName ">" | "<" & identifier ">" XMLValue "</" & identifier ">"
XMLDelimitedItemList ::= XMLDelimitedItem | XMLDelimitedItem XMLDelimitedItemList
XMLEmbeddedPDVValue ::= XMLSequenceValue
XMLEnumeratedValue ::= EmptyElementEnumerated | TextEnumerated
XMLExternalValue ::= XMLSequenceValue
XMLFixedTypeFieldVal ::= XMLBuiltinValue
XMLIdentifierList ::= EmptyElementList | TextList
XMLInstanceOfValue ::= XMLValue
XMLIntegerValue ::= XMLSignedNumber | EmptyElementInteger | TextInteger
XMLIRIValue ::= FirstArcIdentifier SubsequentArcIdentifier
XMLNameAndNumberForm ::= identifier & "(" & XMLNumberForm & ")"
XMLNamedValue ::= "<" & identifier ">" XMLValue "</" & identifier ">"
XMLNullValue ::= empty
XMLNumberForm ::= number
XMLNumericRealValue ::= realnumber | "-" & realnumber
XMLObjectClassFieldValue ::= XMLOpenTypeFieldVal | XMLFixedTypeFieldVal
XMLObjectIdentifierValue ::= XMLObjIdComponentList
XMLObjIdComponent ::= NameForm | XMLNumberForm | XMLNameAndNumberForm
XMLObjIdComponentList ::= XMLObjIdComponent | XMLObjIdComponent & "." & XMLObjIdComponentList
XMLOctetStringValue ::= XMLTypedValue | xmlhstring
XMLOpenTypeFieldVal ::= XMLTypedValue | xmlhstring
XMLPrefixedValue ::= XMLValue
XMLRealValue ::= XMLNumericRealValue | XMLSpecialRealValue
XMLRelativeIRIValue ::= FirstRelativeArcIdentifier SubsequentArcIdentifier
XMLRelativeOIDComponent ::= XMLNumberForm | XMLNameAndNumberForm
XMLRelativeOIDComponentList ::= XMLRelativeOIDComponent | XMLRelativeOIDComponent & "." & XMLRelativeOIDComponentList
XMLRelativeOIDValue ::= XMLRelativeOIDComponentList
XMLRestrictedCharacterStringValue ::= xmlcstring
XMLSequenceOfValue ::= XMLValueList | XMLDelimitedItemList | empty
XMLSequenceValue ::= XMLComponentValueList | empty
XMLSetOfValue ::= XMLValueList | XMLDelimitedItemList | empty
XMLSetValue ::= XMLComponentValueList | empty
XMLSignedNumber ::= number | "-" & number
XMLSpecialRealValue ::= EmptyElementReal | TextReal
XMLTimeValue ::= xmltstring
XMLTypedValue ::= "<" & NonParameterizedTypeName ">" XMLValue "</" & NonParameterizedTypeName ">" | "<" & NonParameterizedTypeName "/>"
XMLUnrestrictedCharacterStringValue ::= XMLSequenceValue
XMLValue ::= XMLBuiltinValue | XMLObjectClassFieldValue
XMLValueAssignment ::= valuereference "::=" XMLTypedValue
XMLValueList ::= XMLValueOrEmpty | XMLValueOrEmpty XMLValueList
XMLValueOrEmpty ::= XMLValue | "<" & NonParameterizedTypeName "/>"
