import type Parser from '../../Parser.mjs';
import OptionalParser from '../../OptionalParser.mjs';
import type ParseContext from '../../interfaces/ParseContext.mjs';
import { default as Production } from '../../Production.mjs';

/**
 * @summary Ignore the error if something cannot be parsed.
 * @description
 * A parser generated by this parser factory will simply ignore failure (meaning
 * that it will succeed), even if the contained `parser` fails to parse
 * successfully. Other than deleting any error, the parser state produced by the
 * contained parser will be returned unchanged.
 *
 * @param {Parser} parser The `Parser` whose failure is to be ignored.
 * @returns {Parser} A `Parser` that will always succeed.
 * @function
 */
export const optional = function (parser: Parser): Parser {
  return new OptionalParser(
    () => `Optional ${parser.name()}`,
    (state: ParseContext): ParseContext => {
      const currentloc = state.tokens[state.index].location;
      const result = parser.execute(state);
      if (result.error) {
        delete result.error;
        if (result.cst.children.length === 0) {
          result.cst = new Production(
            result.cst.type,
            result.cst.children,
            {
              ...currentloc,
              endIndex: currentloc.startIndex,
            },
          );
        }
      }
      return result;
    }
  );
}
;
export default optional;
