import Parser from '../../Parser.mjs';
import ProductionType from '../../ProductionType.mjs';
import literal from './literal.mjs';
import whitespaceTolerantList from './whitespaceTolerantList.mjs';

/**
 * @summary Produce a parser that will parse a period-delimited list of
 *  arbitrary items.
 * @description
 * This parser factory produces a parser that will attempt to parse:
 *
 * - A list item, as determined by the `listItemParser`
 * - An optional whitespace
 * - A period
 * - An optional whitespace
 *
 * In that order, repeating indefinitely until no such productions can be parsed
 * from the input. The last item will always be of the type the `listItemParser`
 * emits; the parser generated by this factory will not consume trailing
 * whitespace or periods.
 *
 * The resulting CSTs of the list productions will all be children of a parent
 * production whose type will be `containingType`.
 *
 * @param {ProductionType} containingType The type of the `Production` that will
 *  subsume the resulting CST.
 * @param {Parser} listItemParser The parser that will parse items of the list.
 * @returns {Parser} A `Parser` that will parse a period-delimited list, whose
 *  list items can be parsed with `listItemParser`.
 * @function
 */
export default function (
  containingType: ProductionType,
  listItemParser: Parser
): Parser {
  return whitespaceTolerantList(
    containingType,
    listItemParser,
    literal(ProductionType.period)
  );
}
