import Parser from '../../Parser.mjs';
import type ParseContext from '../../interfaces/ParseContext.mjs';
import Production from '../../Production.mjs';
import ProductionType from '../../ProductionType.mjs';

/**
 * @summary Parse a specific sequence of grammatical productions in order.
 * @description
 * A `Parser` generated by this parser factory will parse all of the component
 * parsers, which are passed in as the parameter `parsers` in the order given.
 * If any of them fail parsing, the `Parser` generated by this parser factory
 * will return an error.
 * @param {ProductionType} containingType The type of the `Production` by which
 *  all of the component CSTs will be subsumed as children.
 * @param {Parser[]} parsers The components of the sequence, which will be
 *  parsed in order.
 * @returns {Parser} A `Parser` that will parse all of the component parsers
 *  in order and fail if any of them fail.
 * @function
 */
export default function (
  containingType: ProductionType,
  parsers: Parser[]
): Parser {
  return new Parser(
    () => `${containingType} Sequence`,
    (state: ParseContext): ParseContext => {
      if (parsers.length === 0) {
        return state;
      }
      const currentloc = state.tokens[state.index]?.location;
      let nextState: ParseContext = state;
      const results: ParseContext[] = new Array(parsers.length);
      for (let i = 0; i < parsers.length; i++) {
        const result = parsers[i].execute(nextState);
        if (result.error) {
          return {
            ...state,
            cst: new Production(
              containingType,
              results.slice(0, i).map((r) => r.cst),
              (results.length && currentloc)
                ? undefined
                : {
                  ...currentloc,
                  endIndex: currentloc.startIndex,
                },
            ),
            error: true,
          };
        }
        nextState = result;
        results[i] = result;
      }
      return {
        ...state,
        tokens: state.tokens,
        index: nextState.index,
        cst: new Production(
          containingType,
          results.map((r) => r.cst)
        ),
      };
    }
  );
}
