import optional from './optional.mjs';
import whitespace from './whitespace.mjs';
import type Parser from '../../Parser.mjs';
import { ProductionType } from '../../ProductionType.mjs';
import whitespaceIntolerantSequenceOf from './whitespaceIntolerantSequenceOf.mjs';

function spliceInWhitespace(parsers: Parser[]): Parser[] {
  if (parsers.length === 0) {
    return [];
  }
  const spliced: Parser[] = new Array(parsers.length * 2 - 1);
  for (let i = 0; i < parsers.length; i++) {
    spliced[i * 2] = parsers[i];
    if (i < parsers.length - 1) {
      spliced[i * 2 + 1] = optional(whitespace);
    }
  }
  return spliced;
}

/**
 * @summary Parse a specific sequence of grammatical productions in order,
 *  tolerating whitespace between them.
 * @description
 * A `Parser` generated by this parser factory will parse all of the component
 * parsers, which are passed in as the parameter `parsers` in the order given.
 * If any of them fail parsing, the `Parser` generated by this parser factory
 * will return an error.
 * @param {ProductionType} containingType The type of the `Production` by which
 *  all of the component CSTs will be subsumed as children.
 * @param {Parser[]} parsers The components of the sequence, which will be
 *  parsed in order.
 * @returns {Parser} A `Parser` that will parse all of the component parsers
 *  in order and fail if any of them fail.
 * @function
 */
export const whitespaceTolerantSequenceOf = function (
  containingType: ProductionType,
  parsers: Parser[]
): Parser {
  return whitespaceIntolerantSequenceOf(
    containingType,
    spliceInWhitespace(parsers)
  );
}
;
export default whitespaceTolerantSequenceOf;
