import whitespaceIntolerantList from './whitespaceIntolerantList.js';
import type Parser from '../../Parser.js';
import whitespace from './whitespace.js';
import ProductionType from '../../ProductionType.js';

/**
 * @summary Produce a parser that will parse a whitespace-delimited list of
 *  arbitrary items.
 * @description
 * This parser factory produces a parser that will attempt to parse:
 *
 * - A list item, as determined by the `listItemParser`
 * - Whitespace
 *
 * In that order, repeating indefinitely until no such productions can be parsed
 * from the input. The last item will always be of the type the `listItemParser`
 * emits; the parser generated by this factory will not consume trailing
 * whitespace.
 *
 * The resulting CSTs of the list productions will all be children of a parent
 * production whose type will be `containingType`.
 *
 * @param {ProductionType} containingType The type of the `Production` that will
 *  subsume the resulting CST.
 * @param {Parser} listItemParser The parser that will parse items of the list.
 * @returns {Parser} A `Parser` that will parse a whitespace-delimited list,
 *  whose list items can be parsed with `listItemParser`.
 * @function
 */
export default function (
  containingType: ProductionType,
  listItemParser: Parser
): Parser {
  return whitespaceIntolerantList(containingType, listItemParser, whitespace);
}
