import optional from './optional.js';
import whitespace from './whitespace.js';
import Parser from '../../Parser.js';
import ProductionType from '../../ProductionType.js';
import whitespaceIntolerantSequenceOf from './whitespaceIntolerantSequenceOf.js';

function spliceInWhitespace(parsers: Parser[]): Parser[] {
  return parsers.flatMap((p) => [p, optional(whitespace)]).slice(0, -1);
}

/**
 * @summary Parse a specific sequence of grammatical productions in order,
 *  tolerating whitespace between them.
 * @description
 * A `Parser` generated by this parser factory will parse all of the component
 * parsers, which are passed in as the parameter `parsers` in the order given.
 * If any of them fail parsing, the `Parser` generated by this parser factory
 * will return an error.
 * @param {ProductionType} containingType The type of the `Production` by which
 *  all of the component CSTs will be subsumed as children.
 * @param {Parser[]} parsers The components of the sequence, which will be
 *  parsed in order.
 * @returns {Parser} A `Parser` that will parse all of the component parsers
 *  in order and fail if any of them fail.
 * @function
 */
export default function (
  containingType: ProductionType,
  parsers: Parser[]
): Parser {
  return whitespaceIntolerantSequenceOf(
    containingType,
    spliceInWhitespace(parsers)
  );
}
