import { KeywordProductionType } from '../ProductionType.mjs';

/**
 * @summary A mapping of ASN.1 keywords to their production types.
 * @constant
 */
export const keywordToTokenMap: Map<string, KeywordProductionType> = new Map<string, KeywordProductionType>([
  ['ABSENT', KeywordProductionType._ABSENT],
  ['ABSTRACT-SYNTAX', KeywordProductionType._ABSTRACT_SYNTAX],
  ['ALL', KeywordProductionType._ALL],
  ['APPLICATION', KeywordProductionType._APPLICATION],
  ['AUTOMATIC', KeywordProductionType._AUTOMATIC],
  ['BEGIN', KeywordProductionType._BEGIN],
  ['BIT', KeywordProductionType._BIT],
  ['BMPString', KeywordProductionType._BMPString],
  ['BOOLEAN', KeywordProductionType._BOOLEAN],
  ['BY', KeywordProductionType._BY],
  ['CHARACTER', KeywordProductionType._CHARACTER],
  ['CHOICE', KeywordProductionType._CHOICE],
  ['CLASS', KeywordProductionType._CLASS],
  ['COMPONENT', KeywordProductionType._COMPONENT],
  ['COMPONENTS', KeywordProductionType._COMPONENTS],
  ['CONSTRAINED', KeywordProductionType._CONSTRAINED],
  ['CONTAINING', KeywordProductionType._CONTAINING],
  ['DATE', KeywordProductionType._DATE],
  ['DATE-TIME', KeywordProductionType._DATE_TIME],
  ['DEFAULT', KeywordProductionType._DEFAULT],
  ['DEFINITIONS', KeywordProductionType._DEFINITIONS],
  ['DURATION', KeywordProductionType._DURATION],
  ['EMBEDDED', KeywordProductionType._EMBEDDED],
  ['ENCODED', KeywordProductionType._ENCODED],
  ['ENCODING-CONTROL', KeywordProductionType._ENCODING_CONTROL],
  ['END', KeywordProductionType._END],
  ['ENUMERATED', KeywordProductionType._ENUMERATED],
  ['EXCEPT', KeywordProductionType._EXCEPT],
  ['EXPLICIT', KeywordProductionType._EXPLICIT],
  ['EXPORTS', KeywordProductionType._EXPORTS],
  ['EXTENSIBILITY', KeywordProductionType._EXTENSIBILITY],
  ['EXTERNAL', KeywordProductionType._EXTERNAL],
  ['FALSE', KeywordProductionType._FALSE],
  ['FROM', KeywordProductionType._FROM],
  ['GeneralizedTime', KeywordProductionType._GeneralizedTime],
  ['GeneralString', KeywordProductionType._GeneralString],
  ['GraphicString', KeywordProductionType._GraphicString],
  ['IA5String', KeywordProductionType._IA5String],
  ['IDENTIFIER', KeywordProductionType._IDENTIFIER],
  ['IMPLICIT', KeywordProductionType._IMPLICIT],
  ['IMPLIED', KeywordProductionType._IMPLIED],
  ['IMPORTS', KeywordProductionType._IMPORTS],
  ['INCLUDES', KeywordProductionType._INCLUDES],
  ['INSTANCE', KeywordProductionType._INSTANCE],
  ['INSTRUCTIONS', KeywordProductionType._INSTRUCTIONS],
  ['INTEGER', KeywordProductionType._INTEGER],
  ['INTERSECTION', KeywordProductionType._INTERSECTION],
  ['ISO646String', KeywordProductionType._ISO646String],
  ['MAX', KeywordProductionType._MAX],
  ['MIN', KeywordProductionType._MIN],
  ['MINUS-INFINITY', KeywordProductionType._MINUS_INFINITY],
  ['NOT-A-NUMBER', KeywordProductionType._NOT_A_NUMBER],
  ['NULL', KeywordProductionType._NULL],
  ['NumericString', KeywordProductionType._NumericString],
  ['OBJECT', KeywordProductionType._OBJECT],
  ['ObjectDescriptor', KeywordProductionType._ObjectDescriptor],
  ['OCTET', KeywordProductionType._OCTET],
  ['OF', KeywordProductionType._OF],
  ['OID-IRI', KeywordProductionType._OID_IRI],
  ['OPTIONAL', KeywordProductionType._OPTIONAL],
  ['PATTERN', KeywordProductionType._PATTERN],
  ['PDV', KeywordProductionType._PDV],
  ['PLUS-INFINITY', KeywordProductionType._PLUS_INFINITY],
  ['PRESENT', KeywordProductionType._PRESENT],
  ['PrintableString', KeywordProductionType._PrintableString],
  ['PRIVATE', KeywordProductionType._PRIVATE],
  ['REAL', KeywordProductionType._REAL],
  ['RELATIVE-OID', KeywordProductionType._RELATIVE_OID],
  ['RELATIVE-OID-IRI', KeywordProductionType._RELATIVE_OID_IRI],
  ['SEQUENCE', KeywordProductionType._SEQUENCE],
  ['SET', KeywordProductionType._SET],
  ['SETTINGS', KeywordProductionType._SETTINGS],
  ['SIZE', KeywordProductionType._SIZE],
  ['STRING', KeywordProductionType._STRING],
  ['SYNTAX', KeywordProductionType._SYNTAX],
  ['T61String', KeywordProductionType._T61String],
  ['TAGS', KeywordProductionType._TAGS],
  ['TeletexString', KeywordProductionType._TeletexString],
  ['TIME', KeywordProductionType._TIME],
  ['TIME-OF-DAY', KeywordProductionType._TIME_OF_DAY],
  ['TRUE', KeywordProductionType._TRUE],
  ['TYPE-IDENTIFIER', KeywordProductionType._TYPE_IDENTIFIER],
  ['UNION', KeywordProductionType._UNION],
  ['UNIQUE', KeywordProductionType._UNIQUE],
  ['UNIVERSAL', KeywordProductionType._UNIVERSAL],
  ['UniversalString', KeywordProductionType._UniversalString],
  ['UTCTime', KeywordProductionType._UTCTime],
  ['UTF8String', KeywordProductionType._UTF8String],
  ['VideotexString', KeywordProductionType._VideotexString],
  ['VisibleString', KeywordProductionType._VisibleString],
  ['WITH', KeywordProductionType._WITH],
  ['true', KeywordProductionType._true],
  ['false', KeywordProductionType._false],

  // Added in ITU X.680, Amendment 1.
  ['SUCCESSORS', KeywordProductionType._SUCCESSORS],
  ['DESCENDANTS', KeywordProductionType._DESCENDANTS],

  // Removed
  ['ANY', KeywordProductionType._ANY],
  ['DEFINED', KeywordProductionType._DEFINED],
  /**
   * These were commented out because there are actually productions in newer
   * ASN.1 specifications that use these names, such as XSDv2 in
   * ITU X.694-2015, which uses "NOTATION" as a name of a type.
   */
  // [ "MACRO", KeywordProductionType._MACRO ],
  // [ "TYPE", KeywordProductionType._TYPE ],
  // [ "VALUE", KeywordProductionType._VALUE ],
  // [ "NOTATION", KeywordProductionType._NOTATION ],
]);

export default keywordToTokenMap;
